### PR TITLE
Dmsayo/201/file upload

### LINKED ISSUE #201: File Uploads
Images are probably the MVP of this, but supporting that indirectly paves way for files of any kind.  

Rough UI / Flow:

1. Attach icon in Text Input
2. Clicking attach icon opens file browser
3. Selecting file instantly submits file as new message

To keep things simple, I'd like to just store the file on the filesystem.  For this we will add a `engram/chat/be/uploads` folder.

Similar to the public folder we should tell express to serve up static files in this folder with: `app.use("/uploads", express.static('uploads'));`

We can use the multer package for actually uploading the file: https://github.com/expressjs/multer .  

I'd like to create a new database collection for `files`.  

```mermaid
classDiagram
  class Message
    Message : +ObjectID _id
    Message : +ObjectID file
    Message : +ObjectID room

  class File
    File : +ObjectID _id
    File : +String url
    File : +String filename
```

Where `filename` is the initial name of the file.  And `url` is the path to access the file e.g. `/uploads/628f25700000000000000000.png`  Where `628f25700000000000000000` is the actual _id of the file object.

### PR DESCRIPTION
**Pull request by dmsayo**
## Description
Fix #201  add file uploads

### CODE REVIEW

**Review by adamjberg — CHANGES_REQUESTED** [review]
I'm going to make a suggestion that I'm not 100% sold on, but should be possible to start with and migrate in the future if it's ever an issue. 

I think we don't add a `files` collection.  Instead we put a `type` property on Message and have a `type` "file".  We would then have a file object that gets stored within the message when the type is "file".  

I think doing so then answers your question

**Comment by dmsayo** [comment]
Some questions for the Message type:

Do you mean editing this type like so?
```
export type MessageType = {
  _id: string;
  user: string;
  body: string;
  room: string;
  createdAt: Date;
  updatedAt?: Date;
  // Add this?
  type: string; // "file" or "text"?
  file?: {
    _id: string;
    url: string;
    fileName: string; // original file name
  }
};
```

Currently I have the file collection like so:
```
// File in Files collection
{ 
    "_id" : ObjectId("62acfe5fc73c9e840bf66be5"),
    "url" : "uploads/62acfe5fc73c9e840bf66be5.jpg", 
    "filename" : "cat.jpg"
}
```
... which is sent as a message:
```
{ 
    "_id" : ObjectId("62acfe5fc73c9e840bf66be6"), 
    "room" : ObjectId("6286b9a327968162a97c82dd"), 
    "file" : "62acfe5fc73c9e840bf66be5", // file._id right now, doesn't send back url
    "user" : ObjectId("62827c08dfed9351ef6b832d")
}
```
Screenshot from 2022-06-20 11-27-33

**Comment by adamjberg** [comment]
Yup, that's exactly what I'm suggesting.  Which should then give you access to `file.url` so you can render the image.

**Comment by dmsayo** [comment]
Screenshot from 2022-08-19 12-20-23

**Review by adamjberg — APPROVED** [review]

**Pull request merged**
